maxim-redux-slice-refactoring
mcntai/muzsoyuz_react pull request #10
Opened 2021-02-08 13:00 UTC by mcntai

2021-02-08 22:03 UTC, drummer1992 requested changes

2021-02-08 22:03 UTC, drummer1992 commented on src/slice/user.js
> +const fulfilledReducer = (state, action) => {
не зрозуміло чий це редюсер, і чому тут робляться ці join ?

2021-02-08 22:03 UTC, drummer1992 commented on src/slice/utils/load-extra-reducers.js
> +// }
видаляй непотрібний код

2021-02-09 15:40 UTC, mcntai commented on src/slice/user.js
> +const fulfilledReducer = (state, action) => {
Переіменую редюсер. 
В action.payload можуть заходити динамічні параметри, але по одній парі. Як мені старгетити динамічний ключ і значення краще без join?

2021-02-09 16:02 UTC, mcntai commented on src/pages/auth/AuthForm.jsx
> +    this.props.dispatch(authenticateUser({
Форми легше обробляти в класовому компоненті так як введення даних можна занехндлити однією функцією. Те ж саме стосується валідації.

В класових компонентах хендл інпутів стає конченим коли їх багато. Потрібно або під кожен інпут свою функцію або якісь незрозумілі танци з бубном шо код стає нечитабельним.

В даному випадку універсальний setState зручніший ніж окремий сеттер для кожного стейта типа setEmail, setPassword, setConfirmPassword, setEmailError etc.

Поправ мене якшо я помиляюсь

2021-02-09 20:51 UTC, mcntai commented on src/pages/findJobs/sorting/SortingFrom.jsx
> +    const sortType = e.target.getAttribute('datafld')
просто обичний data реакт не приймає. а кебаб-кейс я юзати не хотів бо ніде не юзаю по суті. тому заюзав те, шо реакт приймає. ок переіменував на кебаб-кейс

2021-02-09 23:17 UTC, mcntai commented on src/slice/general.js
> +export const { toggleElement, moveFinishBtnCalendarQuest } = generalSlice.actions
чесно кажучи не бачу в цьому сенсу. слайси треба не тільки для санок. в офіційній доці приклад без санок зроблений в таком ж стилі як і в мене. тулкіт робили для того шоб стандартизувати редакс код в тому числі, шоб кожен не писав як йому вздумається, тому я пропоную залишити так як є шоб весь редакс був в одному стилі

2021-02-10 04:02 UTC, drummer1992 commented on src/slice/general.js
> +export const { toggleElement, moveFinishBtnCalendarQuest } = generalSlice.actions
окей

2021-02-10 04:07 UTC, drummer1992 commented on src/slice/user.js
> +const fulfilledReducer = (state, action) => {
з join я не зрозумів, треба глянути як воно працює

В цьому модулі є екшн `addFreeDays` і він ніде не викликається

2021-02-10 15:46 UTC, mcntai commented on src/pages/auth/AuthForm.jsx
> +    this.props.dispatch(authenticateUser({
переробив, твоя взяла

2021-02-18 07:58 UTC, drummer1992 requested changes

2021-02-18 07:58 UTC, drummer1992 commented on src/actions/user.js
> +}
`history.push(userProfile.role === null ? START_ROUTE : nextLocation)`

2021-02-18 07:58 UTC, drummer1992 commented on src/app/App.jsx
> +    <>
в тебе ж є тут div для чого ще <>?

2021-02-18 07:58 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +const SinglePickCalendar = ({ s }) => {
s ?

такі назви не допустимі

2021-02-18 07:58 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +    if (!ref.current.dates.length) {
!ref.current.dates.length - якщо це можливо то краще перевіряти по флагам санки, loaded, loading

2021-02-18 07:58 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +  }, [selectedDays, workdays])
глянь на попередній коментар

2021-02-18 07:58 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +  }, [selectedDays, workdays])
я хотів би відмовитися від цих стейджів

2021-02-18 07:58 UTC, drummer1992 commented on src/components/common/successMap.js
> +}
буде зручніше коли ти винесеш тексти помилок від сервера в константи, і ми зможемо їх використати ще десь

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/auth/SocialMediaOauth.jsx
> +  )
навіщо тут <>?

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/auth/SocialMediaOauth.jsx
> +  )
() => handleRedirect(user) так не працює?

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/auth/authRedirectHandler.js
> +}
ми можемо винести цю логіку в екшни?

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/findJobs/OpenJob.jsx
> +  }, [])
тут не повинно бути try catch setData не сроває помилки, якщо вони й є то тільки по твоїй вині, наприклаж TypeError якийсь, бо в state немає data

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/findJobs/sorting/SortingFrom.jsx
> +  let visible = display ? s.visible : s.hidden
let? ти ж його наче не міняєш

2021-02-18 07:58 UTC, drummer1992 commented on src/pages/profile/Logout.jsx
> +    dispatch(logout({message: 'logged out'}))
повинось ці error строки в константи

2021-02-18 07:58 UTC, drummer1992 commented on src/reducers/errorsReducer.js
> +  } else if (type === 'CLEAR_ERROR') {
чому це строка?

2021-02-18 07:58 UTC, drummer1992 commented on src/routes/UserProvider.jsx
> +      loading={isProfilePage ? null : loading}
це виглядає як костиль, треба кондішн при апдейті другий використовувати для лоадера

2021-02-18 07:58 UTC, drummer1992 commented on src/routes/UserProvider.jsx
> +      loading={isProfilePage ? null : loading}
якщо тобі знадобиться ще шось апдейтити то шо будемо тут городити гору перевірок?

2021-02-18 07:58 UTC, drummer1992 commented on src/slice/offers.js
> +import { createSlice } from '@reduxjs/toolkit'
тут роблю паузу...

2021-02-18 11:39 UTC, mcntai commented on src/components/common/SinglePickCalendar.jsx
> +const SinglePickCalendar = ({ s }) => {
Тут суть в тому, шо я цей календар використовую в 2 різних місцях і прокидую в пропсах різні CSS стилі. Так як я скрізь використовую модульний css, то в якості змінної я використовую s, типу від style, це цілком адекватна практика в модульному css, я це не сам придумав. Тому і в цей компонент я прокидую його як s, шоб все було уже однаково. Якшо це дуже критично, я можу переіменувати в styles, наприклад, але чому воно так як є зараз, я пояснив

2021-02-18 12:00 UTC, mcntai commented on src/pages/auth/SocialMediaOauth.jsx
> +  )
Наскільки я знаю, то ні, компонент має вернути шось, шо буде огорнуте в будь який тег або фрагмент як тут. Якшо без <></> то WebStorm підсвічує, шо мол React is defined but never used.

Цей компонент треба взагалі переробити нормально, просто я не можу толком це зробити, бо на локалці соц мережі не роблять

2021-02-18 12:03 UTC, mcntai commented on src/pages/auth/authRedirectHandler.js
> +}
ця логіка уже і так винесена в екшени і вона працює для звичайної реєстрації, просто я не видаляв її так як не міг перевірити чи вона точно працює для соц мереж. треба шоб ти підказав як це зробити. коли переконаюсь, шо воно працює, то перероблю компонент з соц мережами,а цей модуль з редіректом взагалі удалю

2021-02-18 12:09 UTC, mcntai commented on src/pages/findJobs/OpenJob.jsx
> +  }, [])
я згоден, шо можливо це виглядає неправильно і це якийсь костиль. ситуація тут така

OpenJob це сторінка детального оголошення. Є 2 варіанти коректного флоу попадання на цю сторінку юзера:
1. Юзер заходить зі сторінки всіх оголошень і тоді я просто прокидую обєкт з даними і рендерю його
2. Юзер сам публікує оголошення і після того як публікує його кидає сюди, мол от подивись як все виглядає.

Але є НЕкоректний сценарій, коли юзер в тупу відкриває ссилку /open-job і тоді відбувається краш, так як в компонент не заходить те, шо я рендерю.

try catch мені допомагає вирішити цю проблему. якшо можна зробити це краще, підкажи як

2021-02-18 13:03 UTC, mcntai commented on src/routes/UserProvider.jsx
> +      loading={isProfilePage ? null : loading}
це складний кейс для мене, тут треба голосом обсудити. я просто не хочу тут розписувати портянку в чому саме причина складності

2021-02-18 13:21 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +const SinglePickCalendar = ({ s }) => {
цей модуль `CalendarProfile.module.css` взагалі не повинен знаходитися в модулі `Profile.jsx`
він повинен бути десь в common і імпортувався всім кому він треба, прокидувати його нікуди не треба

2021-02-18 13:27 UTC, drummer1992 commented on src/components/common/SinglePickCalendar.jsx
> +const SinglePickCalendar = ({ s }) => {
хоча, може в твоєму випадку і ок, але я б назвав хоча б styles, від s мене коробить)

2021-02-18 13:37 UTC, drummer1992 requested changes

2021-02-18 13:37 UTC, drummer1992 commented on src/utils/muzsoyuz/setDataToLS.js
> +}
помоєму це вже можна видалити

2021-02-18 13:37 UTC, drummer1992 commented on src/utils/request.js
> +
видали якщо тобі не потрібне це логування

2021-02-18 13:40 UTC, drummer1992 commented on src/pages/auth/SocialMediaOauth.jsx
> +  )
то видали імпорт React в цьому модулі, він свариться бо ти його заімпортив а jsx немає

2021-02-18 13:41 UTC, drummer1992 commented on src/pages/auth/authRedirectHandler.js
> +}
то видаляй зараз, якшо не буде робити то потом пофіксим

2021-02-18 13:45 UTC, drummer1992 commented on src/pages/findJobs/OpenJob.jsx
> +  }, [])
в компонент нічого не заходить `const OpenJob = () =>`
```
if (location?.state?.data) {
        setData([location?.state?.data]) 
      } else {
        dispatch(goTo(r.FIND_JOB))
      }
```

2021-02-18 14:45 UTC, mcntai commented on src/pages/findJobs/OpenJob.jsx
> +  }, [])
норм, я мабуть до кінця не розумію як працює цей ?. 
тому шо я пробував використати його, просто шось не получалось)

хотя хз шо там могло не получитись...ну вже ладно)

2021-02-20 22:21 UTC, merged